version: "3.8"
services:
  mysql_db:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    links:
      - mysql_db:mysql_db
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ''
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "8081:80"
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: